-- =============================================================================
-- PostgREST demo schema
--
-- The core idea: this file IS the API. There are no route handlers anywhere in
-- this project. Every endpoint below is generated by PostgREST from what's
-- declared here — tables, views, and functions become URLs; Postgres roles and
-- RLS policies become the authorization layer.
-- =============================================================================

-- PostgREST exposes exactly ONE schema over HTTP. Anything outside it is
-- invisible to the API. This is the first and most important boundary:
-- put private tables in `public`, put the API surface in `api`.
CREATE SCHEMA IF NOT EXISTS api;

-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------

CREATE TABLE api.branches (
  id          serial PRIMARY KEY,
  name        text NOT NULL,
  postcode    text NOT NULL,
  lat         double precision NOT NULL,
  lon         double precision NOT NULL,
  -- Two independent visibility flags, mirroring a real-world pattern:
  -- a branch can be active but still hidden from public/consumer listings.
  is_active   boolean NOT NULL DEFAULT true,
  show_on_b2c boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE api.enquiries (
  id         serial PRIMARY KEY,
  branch_id  integer NOT NULL REFERENCES api.branches(id) ON DELETE CASCADE,
  name       text NOT NULL,
  email      text NOT NULL,
  message    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Seed data
-- Note the deliberate mix: some branches are B2C-visible, some are active but
-- internal-only, one is fully inactive. This lets the RLS policy below actually
-- demonstrate something rather than being a no-op.
-- -----------------------------------------------------------------------------

INSERT INTO api.branches (name, postcode, lat, lon, is_active, show_on_b2c) VALUES
  ('Leicester',       'LE1 1AA', 52.6369, -1.1398, true,  true),
  ('Nottingham',      'NG1 2BB', 52.9548, -1.1581, true,  true),
  ('Birmingham',      'B1 1AA',  52.4862, -1.8904, true,  true),
  ('Coventry',        'CV1 1AA', 52.4068, -1.5197, true,  true),
  ('Derby',           'DE1 1AA', 52.9225, -1.4746, true,  true),
  ('Sheffield',       'S1 1AA',  53.3811, -1.4701, true,  true),
  ('Manchester',      'M1 1AA',  53.4808, -2.2426, true,  true),
  ('Rugby Depot',     'CV21 1AA',52.3705, -1.2645, true,  false), -- active, internal only
  ('Tamworth Depot',  'B79 7AA', 52.6339, -1.6947, true,  false), -- active, internal only
  ('Closed Warehouse','LE9 1AA', 52.5800, -1.2500, false, false); -- inactive entirely

-- -----------------------------------------------------------------------------
-- Views — the idiomatic PostgREST pattern.
--
-- You rarely expose raw tables. A view lets you control exactly which columns
-- and rows form the public contract, independently of how the table evolves.
-- The view IS the endpoint: this one becomes GET /public_branches
-- -----------------------------------------------------------------------------

CREATE VIEW api.public_branches AS
  SELECT id, name, postcode, lat, lon
  FROM api.branches
  WHERE is_active = true
    AND show_on_b2c = true;

-- -----------------------------------------------------------------------------
-- Function → RPC endpoint.
--
-- Becomes POST /rpc/branches_near — a real query (haversine distance) exposed
-- as HTTP with zero application code. STABLE tells Postgres it doesn't mutate,
-- which also lets PostgREST expose it over GET if desired.
-- -----------------------------------------------------------------------------

CREATE FUNCTION api.branches_near(
  lat double precision,
  lon double precision,
  radius_miles double precision DEFAULT 50
)
RETURNS TABLE (
  id       integer,
  name     text,
  postcode text,
  distance double precision
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    b.id,
    b.name,
    b.postcode,
    (3959 * ACOS(
      COS(RADIANS(branches_near.lat)) * COS(RADIANS(b.lat)) *
      COS(RADIANS(b.lon) - RADIANS(branches_near.lon)) +
      SIN(RADIANS(branches_near.lat)) * SIN(RADIANS(b.lat))
    )) AS distance
  FROM api.branches b
  WHERE (3959 * ACOS(
      COS(RADIANS(branches_near.lat)) * COS(RADIANS(b.lat)) *
      COS(RADIANS(b.lon) - RADIANS(branches_near.lon)) +
      SIN(RADIANS(branches_near.lat)) * SIN(RADIANS(b.lat))
    )) < branches_near.radius_miles
  ORDER BY distance ASC;
$$;

-- =============================================================================
-- Roles & authorization
--
-- This is the part that makes PostgREST's security model work, and it's the
-- bit most worth understanding.
--
-- `authenticator` is deliberately POWERLESS. It can log in, but owns no data
-- access of its own (NOINHERIT is doing real work here — it prevents the role
-- from automatically inheriting the privileges of roles granted to it).
-- Per request, PostgREST switches from `authenticator` into whichever role the
-- request is entitled to: `web_anon` for unauthenticated calls, or a role named
-- in a JWT claim for authenticated ones.
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticator') THEN
    CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'authpassword';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'web_anon') THEN
    CREATE ROLE web_anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'web_user') THEN
    CREATE ROLE web_user NOLOGIN;
  END IF;
END
$$;

-- --- Anonymous role: read-only, and only what's public -----------------------
GRANT USAGE ON SCHEMA api TO web_anon;

-- Anonymous can read the curated view, but NOT the underlying table.
GRANT SELECT ON api.public_branches TO web_anon;

-- Anonymous CAN read the branches table too — but RLS (below) will restrict
-- which rows are visible. This demonstrates the difference between the two
-- approaches: the view filters by construction, RLS filters by policy.
GRANT SELECT ON api.branches TO web_anon;

-- Anonymous can submit an enquiry (INSERT) but cannot read enquiries back.
-- This is a genuinely useful asymmetry — a public contact form.
GRANT INSERT ON api.enquiries TO web_anon;
GRANT USAGE, SELECT ON SEQUENCE api.enquiries_id_seq TO web_anon;

GRANT EXECUTE ON FUNCTION api.branches_near TO web_anon;

-- --- Authenticated role: full read, plus writes ------------------------------
GRANT USAGE ON SCHEMA api TO web_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.branches TO web_user;
GRANT SELECT ON api.public_branches TO web_user;
GRANT SELECT, INSERT, DELETE ON api.enquiries TO web_user;
GRANT USAGE, SELECT ON SEQUENCE api.branches_id_seq TO web_user;
GRANT USAGE, SELECT ON SEQUENCE api.enquiries_id_seq TO web_user;
GRANT EXECUTE ON FUNCTION api.branches_near TO web_user;

-- Let the authenticator switch into either role.
GRANT web_anon TO authenticator;
GRANT web_user TO authenticator;

-- =============================================================================
-- Row Level Security
--
-- The key insight: this is enforced by the DATABASE, not by the API layer.
-- An anonymous caller physically cannot retrieve a hidden row — not because
-- PostgREST filters the response, but because Postgres won't return it. No
-- malformed query, injection, or forgotten `WHERE` clause in application code
-- can bypass it. It fails CLOSED by default.
-- =============================================================================

ALTER TABLE api.branches ENABLE ROW LEVEL SECURITY;

-- Anonymous callers see only active, B2C-visible branches.
CREATE POLICY branches_anon_select ON api.branches
  FOR SELECT
  TO web_anon
  USING (is_active = true AND show_on_b2c = true);

-- Authenticated callers see everything, including internal depots.
CREATE POLICY branches_user_all ON api.branches
  FOR ALL
  TO web_user
  USING (true)
  WITH CHECK (true);

ALTER TABLE api.enquiries ENABLE ROW LEVEL SECURITY;

-- Anonymous can insert an enquiry but can never select one back out.
CREATE POLICY enquiries_anon_insert ON api.enquiries
  FOR INSERT
  TO web_anon
  WITH CHECK (true);

CREATE POLICY enquiries_user_all ON api.enquiries
  FOR ALL
  TO web_user
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- Tell PostgREST to reload its schema cache.
-- (It caches the schema on boot; this NOTIFY makes it pick up changes live.)
-- =============================================================================
NOTIFY pgrst, 'reload schema';
